// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { fakeBrowser } from 'wxt/testing';
  export { resetScanSignature, resetContentState, getWordList, proceedWithSiteListCheck, cancelScheduledScan, scheduleScan, deferUntilPageIdle, performScan, performStandardScan, performHighlightScan, scanWithWorkerForHighlights, getTextNodes, applyHighlights, clearHighlights, updateHighlightStyle, getBodyTextSnapshot, getScanWorkerAsync, setupWorkerListeners, handleWorkerMessage, cleanupWorker, scanWithWorker, getChunkingConfig, sendKeywordCount, setupObserver, debounce } from '../utils/content-core';
  export { normalizeKeywords, buildCombinedRegex, scanTextForKeywords, scanTextForMatches, hashString } from '../utils/scanner';
  export { SETTINGS_VERSION_KEY, SETTINGS_VERSION, DEFAULT_SETTINGS, applySettingsDefaults, getSettings, ensureSettingsInitialized } from '../utils/settings';
  export { saveToStorage, getFromStorage, showAlert, isValidObj, trimAndClean, logit, getRandomInt, buildSiteRegex, isUrlAllowed, compileSitePatterns, isUrlAllowedCompiled, buildPatternsForTab, partitionKeywordPatterns, partitionSitePatterns, mergeUnique } from '../utils/utils';
}
