// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_SETTINGS: typeof import('/app/utils/settings').DEFAULT_SETTINGS
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const SETTINGS_VERSION: typeof import('/app/utils/settings').SETTINGS_VERSION
  const SETTINGS_VERSION_KEY: typeof import('/app/utils/settings').SETTINGS_VERSION_KEY
  const applyHighlights: typeof import('/app/utils/content-core').applyHighlights
  const applySettingsDefaults: typeof import('/app/utils/settings').applySettingsDefaults
  const browser: typeof import('wxt/browser').browser
  const buildCombinedRegex: typeof import('/app/utils/scanner').buildCombinedRegex
  const buildPatternsForTab: typeof import('/app/utils/utils').buildPatternsForTab
  const buildSiteRegex: typeof import('/app/utils/utils').buildSiteRegex
  const cancelScheduledScan: typeof import('/app/utils/content-core').cancelScheduledScan
  const cleanupWorker: typeof import('/app/utils/content-core').cleanupWorker
  const clearHighlights: typeof import('/app/utils/content-core').clearHighlights
  const compileSitePatterns: typeof import('/app/utils/utils').compileSitePatterns
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const debounce: typeof import('/app/utils/content-core').debounce
  const deferUntilPageIdle: typeof import('/app/utils/content-core').deferUntilPageIdle
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const ensureSettingsInitialized: typeof import('/app/utils/settings').ensureSettingsInitialized
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getBodyTextSnapshot: typeof import('/app/utils/content-core').getBodyTextSnapshot
  const getChunkingConfig: typeof import('/app/utils/content-core').getChunkingConfig
  const getFromStorage: typeof import('/app/utils/utils').getFromStorage
  const getRandomInt: typeof import('/app/utils/utils').getRandomInt
  const getScanWorkerAsync: typeof import('/app/utils/content-core').getScanWorkerAsync
  const getSettings: typeof import('/app/utils/settings').getSettings
  const getTextNodes: typeof import('/app/utils/content-core').getTextNodes
  const getWordList: typeof import('/app/utils/content-core').getWordList
  const handleWorkerMessage: typeof import('/app/utils/content-core').handleWorkerMessage
  const hashString: typeof import('/app/utils/scanner').hashString
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isUrlAllowed: typeof import('/app/utils/utils').isUrlAllowed
  const isUrlAllowedCompiled: typeof import('/app/utils/utils').isUrlAllowedCompiled
  const isValidObj: typeof import('/app/utils/utils').isValidObj
  const logit: typeof import('/app/utils/utils').logit
  const mergeUnique: typeof import('/app/utils/utils').mergeUnique
  const normalizeKeywords: typeof import('/app/utils/scanner').normalizeKeywords
  const partitionKeywordPatterns: typeof import('/app/utils/utils').partitionKeywordPatterns
  const partitionSitePatterns: typeof import('/app/utils/utils').partitionSitePatterns
  const performHighlightScan: typeof import('/app/utils/content-core').performHighlightScan
  const performScan: typeof import('/app/utils/content-core').performScan
  const performStandardScan: typeof import('/app/utils/content-core').performStandardScan
  const proceedWithSiteListCheck: typeof import('/app/utils/content-core').proceedWithSiteListCheck
  const resetContentState: typeof import('/app/utils/content-core').resetContentState
  const resetScanSignature: typeof import('/app/utils/content-core').resetScanSignature
  const saveToStorage: typeof import('/app/utils/utils').saveToStorage
  const scanTextForKeywords: typeof import('/app/utils/scanner').scanTextForKeywords
  const scanTextForMatches: typeof import('/app/utils/scanner').scanTextForMatches
  const scanWithWorker: typeof import('/app/utils/content-core').scanWithWorker
  const scanWithWorkerForHighlights: typeof import('/app/utils/content-core').scanWithWorkerForHighlights
  const scheduleScan: typeof import('/app/utils/content-core').scheduleScan
  const sendKeywordCount: typeof import('/app/utils/content-core').sendKeywordCount
  const setupObserver: typeof import('/app/utils/content-core').setupObserver
  const setupWorkerListeners: typeof import('/app/utils/content-core').setupWorkerListeners
  const showAlert: typeof import('/app/utils/utils').showAlert
  const storage: typeof import('wxt/utils/storage').storage
  const trimAndClean: typeof import('/app/utils/utils').trimAndClean
  const updateHighlightStyle: typeof import('/app/utils/content-core').updateHighlightStyle
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
