// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/assets/48.png"
    | "/assets/ws128.png"
    | "/assets/ws16.png"
    | "/assets/ws24.png"
    | "/assets/ws32.png"
    | "/assets/ws48.png"
    | "/background.js"
    | "/css/index.css"
    | "/injected.js"
    | "/js/scan-worker.js"
    | "/js/scanner.js"
    | "/options.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
